package assignment2;


/**
* FileSharingApp/FileSharingPackage/FileInfoListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Thursday, February 22, 2024 2:40:35 o'clock AM EST
*/

public final class FileInfoListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public FileInfoListHolder ()
  {
  }

  public FileInfoListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileInfoListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileInfoListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileInfoListHelper.type ();
  }

}
