package FileSharingApp.FileSharingPackage;


/**
* FileSharingApp/FileSharingPackage/FileInfoListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Wednesday, February 21, 2024 3:39:30 o'clock PM EST
*/

public final class FileInfoListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public FileInfoListHolder ()
  {
  }

  public FileInfoListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSharingApp.FileSharingPackage.FileInfoListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSharingApp.FileSharingPackage.FileInfoListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSharingApp.FileSharingPackage.FileInfoListHelper.type ();
  }

}
