package assignment2.FileSharingApp;


/**
* FileSharingApp/FileSharingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Thursday, February 22, 2024 2:40:34 o'clock AM EST
*/


// Interface for P2P file sharing services
abstract public class FileSharingHelper
{
  private static String  _id = "IDL:FileSharingApp/FileSharing:1.0";

  public static void insert (org.omg.CORBA.Any a, FileSharing that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static String[] extract (org.omg.CORBA.Any a)
  {
    return assignment2.FileSharingApp.FileSharingPackage.FileInfoListHelper.read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileSharingHelper.id (), "FileSharing");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static assignment2.FileSharingApp.FileSharing read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileSharingStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileSharing value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileSharing narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharing)
      return (FileSharing)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileSharingStub stub = new _FileSharingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileSharing unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharing)
      return (FileSharing)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileSharingStub stub = new _FileSharingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
