package FileSharingApp;


/**
* FileSharingApp/FileSharing.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Wednesday, February 21, 2024 3:39:30 o'clock PM EST
*/


// Interface for P2P file sharing services
public interface FileSharing extends FileSharingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSharing
