package assignment2.FileSharingApp;

/**
* FileSharingApp/FileSharingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Thursday, February 22, 2024 2:40:34 o'clock AM EST
*/


// Interface for P2P file sharing services
public final class FileSharingHolder implements org.omg.CORBA.portable.Streamable
{
  public assignment2.FileSharingApp.FileSharing value = null;
  public String[] str = null;

  public FileSharingHolder ()
  {
  }

  public FileSharingHolder (FileSharing initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    str = assignment2.FileSharingApp.FileSharingPackage.FileInfoListHelper.read(i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSharingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSharingHelper.type ();
  }

}
