package assignment2.FileSharingApp;


/**
* FileSharingApp/FileSharing.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Thursday, February 22, 2024 2:40:35 o'clock AM EST
*/


// Interface for P2P file sharing services
public interface FileSharing extends FileSharingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSharing
