package assignment2.FileSharingApp;


/**
* FileSharingApp/FileSharingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Thursday, February 22, 2024 2:40:35 o'clock AM EST
*/


// Interface for P2P file sharing services
public interface FileSharingOperations 
{

  // Registers a file with the server to be shared with others
  void registerFile (String filename, String clientID, String clientAddress, String clientPort);

  // Removes a file from the list of shared files
  void removeFile (String filename, String clientID);

  // Searches for a file by name and returns a list of files matching the query
  String[] searchFile (String filename);

  // Retrieves the owner information for a specific file
  String getFileOwner (String filename);
} // interface FileSharingOperations
