package FileSharingApp;


/**
* FileSharingApp/FileSharingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Wednesday, February 21, 2024 3:39:30 o'clock PM EST
*/


// Interface for P2P file sharing services
abstract public class FileSharingHelper
{
  private static String  _id = "IDL:FileSharingApp/FileSharing:1.0";

  public static void insert (org.omg.CORBA.Any a, FileSharingApp.FileSharing that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileSharingApp.FileSharing extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileSharingApp.FileSharingHelper.id (), "FileSharing");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileSharingApp.FileSharing read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileSharingStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileSharingApp.FileSharing value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileSharingApp.FileSharing narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharingApp.FileSharing)
      return (FileSharingApp.FileSharing)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSharingApp._FileSharingStub stub = new FileSharingApp._FileSharingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileSharingApp.FileSharing unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharingApp.FileSharing)
      return (FileSharingApp.FileSharing)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FileSharingApp._FileSharingStub stub = new FileSharingApp._FileSharingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
