package FileSharingApp;

/**
* FileSharingApp/FileSharingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharing.idl
* Wednesday, February 21, 2024 3:39:30 o'clock PM EST
*/


// Interface for P2P file sharing services
public final class FileSharingHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSharingApp.FileSharing value = null;

  public FileSharingHolder ()
  {
  }

  public FileSharingHolder (FileSharingApp.FileSharing initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSharingApp.FileSharingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSharingApp.FileSharingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSharingApp.FileSharingHelper.type ();
  }

}
